# Generated by Django 2.2.4 on 2019-09-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oddam_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=70)),
            ],
        ),
    ]
